### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
### 변수 설정
@baseUrl = http://localhost:8080

### 회원가입 테스트
POST {{baseUrl}}/api/accounts/signup
Content-Type: application/json

{
  "email": "tes123t@example.com",
  "password": "1234",
  "name": "홍길동12314",
  "phone": "010-1234-5678"
}

### 동일 이메일로 재가입 시도 (중복 체크 로직 확인용 - 400 에러 떠야 정상)
POST {{baseUrl}}/api/accounts/signup
Content-Type: application/json

{
  "email": "mys0904@naver.com",
  "password": "1234",
  "name": "문유식",
  "phone": "010-9999-8888"
}

### 필수값 누락 테스트 (email 없이 요청)
POST {{baseUrl}}/api/accounts/signup
Content-Type: application/json

{
  "password": "1234",
  "name": "테스트",
  "phone": "010-0000-0000"
}

### 로그인 테스트
POST {{baseUrl}}/api/accounts/login
Content-Type: application/json

{
  "email": "mys0904@naver.com",
  "password": "135582"
}

### 정보조회 테스트
GET {{baseUrl}}/api/accounts/1
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyMiIsImVtYWlsIjoidGVzMTIzdEBleGFtcGxlLmNvbSIsImlhdCI6MTc4ODE0MzI0MywiZXhwIjoxNzg4MTQ2ODQzfQ.X98DiGs6yUvKCQwg4OMpO4XK-XSJ4mdIQoQPQHsmtVcsIqSLFlGYc0I8H25-RlYefHUuxYb0nWu6j5PS1qkCDg"
}

### 아이디(이메일) 찾기 테스트
POST {{baseUrl}}/api/accounts/find-id
Content-Type: application/json

{
  "name": "문유식",
  "phone": "010-9999-8888"
}

### 비밀번호 찾기 테스트
POST {{baseUrl}}/api/accounts/find-password
Content-Type: application/json

{
  "email" : "mys0904@naver.com"
}