spring.application.name=nubi

#mybatis, jpa 공통 설정
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/accommodation_db
spring.datasource.username=root
spring.datasource.password=1234

# jpa 설정
# JPA 쿼리문 확인 가능
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

jwt.secret=여기에충분히긴랜덤문자열을넣으세요최소32바이트이상권장
jwt.expiration-ms=3600000